### ISSUE TITLE
Add support for values starting with  '-'

### ISSUE THREAD

**Issue by dhondgepooja** [davidledwards/scalop#6]
Currently if the value for an option starts with '-', the parser treats it as an option. I found a similar issue here[1]. I am not sure if it's the best way to handle it. Another option I could think of is escape it using some character.

[1] https://github.com/scallop/scallop/issues/94

**Comment by davidledwards** [comment]
Yes, that seems like an important edge case to support. I think the most reasonable and obvious solution is to escape the character using `\`.

Examples:
```
foo --path \\-file
foo --path "\-file"
```

In both cases, the option parser would see `\-file` as the argument and would interpret the `-` as literal.

In cases where you want `\` to be interpreted literally, then you'd have to double escape as follows:
```
foo --path \\\\-file
foo --path "\\\-file"
```

Does this seem like a reasonable solution?

**Comment by dhondgepooja** [comment]
Yes, that's exactly what I had in mind. It seems like a better approach.

**Comment by dhondgepooja** [comment]
I have created a pull request for this here[1]

[1]https://github.com/davidledwards/scalop/pull/7

**Comment by davidledwards** [comment]
Thanks for the pull request. Just released a new version with escaping support.

https://github.com/davidledwards/scalop/tree/release-2.1
